services:
  db:
    image: postgres:18.1-alpine3.22
    container_name: db
    environment:
      POSTGRES_DB: trenero
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - trenero-network

  backend:
    image: krivolapovdev/backend:${IMAGE_TAG:-latest}
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/trenero
      DB_USERNAME: ${DB_USERNAME:-username}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      GOOGLE_WEB_CLIENT_ID: ${GOOGLE_WEB_CLIENT_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-jwt-ultra-secure-and-ultra-long-secret}
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.middlewares=backend-compress"
      - "traefik.http.middlewares.backend-compress.compress=true"
      - "traefik.http.routers.backend.priority=100"
    networks:
      - trenero-network

  frontend:
    image: krivolapovdev/frontend:${IMAGE_TAG:-latest}
    container_name: frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`) && !PathPrefix(`/api`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.middlewares=frontend-compress"
      - "traefik.http.middlewares.frontend-compress.compress=true"
      - "traefik.http.routers.frontend.priority=10"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - trenero-network

  traefik:
    image: traefik:v3.6.7
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.format=common"
      - "--ping=true"
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping", "--ping.entrypoint=web" ]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - trenero-network

volumes:
  db-data:

networks:
  trenero-network:
    driver: bridge
