services:
  db:
    restart: unless-stopped

  db-backup:
    restart: unless-stopped

  backend:
    restart: unless-stopped

  frontend:
    restart: unless-stopped

  traefik:
    restart: unless-stopped
