services:
  db:
    ports:
      - "5432:5432"
    restart: no

  db-backup:
    restart: no

  backend:
    ports:
      - "8080:8080"
    restart: no

  frontend:
    ports:
      - "3000:3000"
    restart: no

  traefik:
    restart: no
