services:
  db:
    ports: !reset []
    restart: unless-stopped

  backend:
    build: !reset null
    ports: !reset []
    image: krivolapovdev/backend:latest
    restart: unless-stopped

  nginx:
    build: !reset null
    image: krivolapovdev/nginx:latest
    restart: unless-stopped
