services:
  db:
    image: postgres:18.1-alpine3.22
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trenero
      - POSTGRES_USER=${POSTGRES_USER:-username}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: no
