services:
  db:
    restart: unless-stopped

  db-backup:
    image: prodrigestivill/postgres-backup-local:18-alpine-d257e5d
    container_name: db-backup
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: trenero
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      SCHEDULE: "@daily"
      BACKUP_SUFFIX: ".sql.gz"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080" ]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - ~/trenero_backups:/backups
    networks:
      - trenero-network
    restart: unless-stopped

  backend:
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true"
    restart: unless-stopped

  frontend:
    restart: unless-stopped

  traefik:
    restart: unless-stopped
