services:
  db:
    image: postgres:18.1-alpine3.22
    container_name: db
    environment:
      POSTGRES_DB: trenero
      POSTGRES_USER: ${DB_USERNAME:-username}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 20

  db-backup:
    image: prodrigestivill/postgres-backup-local:18-alpine-d257e5d
    container_name: db-backup
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=trenero
      - POSTGRES_USER=${DB_USERNAME:-username}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_SUFFIX=.sql.gz
    volumes:
      - ./backups:/backups

  backend:
    image: krivolapovdev/backend:${IMAGE_TAG:-latest}
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/trenero
      DB_USERNAME: ${DB_USERNAME:-username}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      GOOGLE_WEB_CLIENT_ID: ${GOOGLE_WEB_CLIENT_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-jwt-ultra-secure-and-ultra-long-secret}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  nginx:
    image: krivolapovdev/nginx:${IMAGE_TAG:-latest}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  db-data:
