server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
  datasource:
    driverClassName: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
jwt:
  secret-key: your-jwt-ultra-secure-and-ultra-long-secret
  access-token-expiration: 15m
  refresh-token-expiration: 7d
oauth2:
  google:
    client-id: ${EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID}
