server:
  port: 8080
spring:
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/trenero}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${DB_URL:${spring.datasource.url}}
    user: ${DB_USERNAME:${spring.datasource.username}}
    password: ${DB_PASSWORD:${spring.datasource.password}}
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
jwt:
  secret-key: ${JWT_SECRET_KEY:your-jwt-ultra-secure-and-ultra-long-secret}
  access-token-expiration: 15m
  refresh-token-expiration: 7d
oauth2:
  google:
    client-id: ${GOOGLE_WEB_CLIENT_ID}
