name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake & Push All Images
        uses: docker/bake-action@v6
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          files: ./docker-bake.hcl

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy via SSH
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          private_key_filename: id_rsa
          private_key_value: ${{ secrets.SERVER_SSH_KEY }}
          commands: |
            cd ~/trenero

            git fetch && git reset origin/main --hard

            export IMAGE_TAG="${{ github.sha }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DOCKERHUB_TOKEN="${{ secrets.DOCKERHUB_TOKEN }}"
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            export GOOGLE_WEB_CLIENT_ID="${{ secrets.GOOGLE_WEB_CLIENT_ID }}"
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"
            export REVIEWER_SECRET_KEY="${{ secrets.REVIEWER_SECRET_KEY }}"

            docker compose -p trenero -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose -p trenero -f docker-compose.yml -f docker-compose.prod.yml up -d --wait
            docker image prune -f
